// pages/auth.vue
<script setup lang="ts">
import auth from "~/middleware/auth";

const { t } = useI18n();

const discordEndpoint = baseUrl + ENDPOINTS.Security.discord;
const githubEndpoint = baseUrl + ENDPOINTS.Security.github;

definePageMeta({
  middleware: [auth],
});
</script>

<template>
  <div class="py-6 sm:py-8 lg:py-12">
    <div class="mx-auto max-w-screen-2xl px-4 md:px-8">
      <h2 class="mb-4 text-center text-2xl font-bold md:mb-8 lg:text-3xl">
        {{ t("auth.login") }}
      </h2>
      <div class="mx-auto max-w-lg rounded-lg border">
        <AuthLogin />

        <div class="flex flex-col gap-4 px-4">
          <div class="relative flex items-center justify-center">
            <span class="bg-base-content absolute inset-x-0 h-px"></span>
            <span class="bg-base-100 relative px-4 text-sm">
              Log in with social
            </span>
          </div>

          <a
            class="btn-accent btn flex items-center justify-center gap-2 px-8 py-2 transition duration-100"
            :href="githubEndpoint"
          >
            <Icon name="lucide:github" height="none" />
            Continue with github
          </a>
          <a
            class="btn-secondary btn flex items-center justify-center gap-2 px-8 py-2 transition duration-100"
            :href="discordEndpoint"
          >
            <Icon name="ic:baseline-discord" height="none" />
            Continue with discord
          </a>
        </div>

        <div class="flex items-center justify-center p-4">
          <p class="text-center text-sm">
            Don't have an account?
            <a class="text-secondary transition duration-100"> Register </a>
          </p>
        </div>
      </div>
    </div>
  </div>
</template>

<style scoped></style>

// src/components/index/Auth.tsx
/** @jsxImportSource solid-js */

import { createSignal,  onMount } from "solid-js"
import { Icon } from "@iconify-icon/solid"
import {t} from "i18next";

export default function Auth() {
	const [username, setUsername] = createSignal("")
	const [password, setPassword] = createSignal("")
	const login = async () => {}

	onMount(async () => {})

	return (
		<>
			<div class="flex flex-col gap-4 p-4 md:p-8">
				<div class="">
					<label class="label">
						<span class="label-text">auth.email</span>
					</label>
					<input
						type="text"
						placeholder="Enter your username"
						class="input-bordered input w-full px-3 py-2 transition duration-100"
						onChange={(ev) => setUsername(ev.currentTarget.value)}
						value={username()}
					/>
				</div>

				<div class="">
					<label class="label">
						<span class="label-text">{t("auth.password")}</span>
					</label>
					<input
						type="password"
						placeholder="Enter your password"
						class="input-bordered input w-full px-3 py-2 transition duration-100"
						onChange={(ev) => setPassword(ev.currentTarget.value)}
						value={password()}
					/>
				</div>

				<button
					onClick={login}
					class="btn-primary btn px-8 py-3 transition duration-100"
				>
					"auth.login"
				</button>

				<div class="relative flex items-center justify-center">
					<span class="absolute inset-x-0 h-px bg-base-content"></span>
					<span class="relative bg-base-100 px-4 text-sm">
						Log in with social
					</span>
				</div>

				<button class="btn-accent btn flex items-center justify-center gap-2 px-8 py-3 transition duration-100">
					<Icon icon="lucide:github" />
					Continue with github
				</button>
			</div>
		</>
	)
}
